import React from 'react';
import Head from 'next/head';
import Navbar from './Navbar';

const Layout = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      {children}
    </>
  );
};

export default Layout;
