import { GetStaticProps } from "next";
import Head from 'next/head';
import { getAllPosts } from "../lib/notionAPI";
import TopPost from "../components/topPost";

export const getStaticProps: GetStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },
    revalidate: 10,
  };
};

export default function Home({allPosts}: any) {
  console.log(allPosts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto py-4">
          <h2 className="text-3xl font-bold text-amber-400 md:text-emerald-600 text-center">
            ブログ記事🐰
        </h2>
        
        <div className="px-4 sm:px-6 lg:px-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 lg:gap-6">
          {allPosts.map((card: any) => (
            <TopPost card={card} key={card.id} />
          ))}
        </div>
      </main>
    </>
  )
}
