import { GetStaticProps } from "next";
import Head from 'next/head';
import { getAllPosts } from "../lib/notionAPI";

export const getStaticProps: GetStaticProps = async () => {
  const allPosts = await getAllPosts();

  return {
    props: {
      allPosts,
    },
    revalidate: 10,
  };
};

export default function Home({allPosts}) {
  console.log(allPosts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <h2 className="text-3xl font-bold underline text-amber-400 md:text-emerald-600">
            Hello world!
          </h2>
      </main>
    </>
  )
}
